### ISSUE TITLE
examples/demo_async_std.rs  run error when duration 30s

### ISSUE THREAD

**Issue by elderbig** [BinChengZhao/delay-timer#25]
**examples/demo_async_std.rs run error**

**To Reproduce**
add  a time to continue,like bellow
``` rust
    thread::sleep(Duration::from_secs(20));
    Ok(delay_timer.stop_delay_timer()?)
```
edit function build_task_async_execute_process() ,when shedule like "*/1 * * * * * *",it is run well.
```rust
fn build_task_async_execute_process() -> Result<Task, TaskError> {
    let mut task_builder = TaskBuilder::default();

    let body = unblock_process_task_fn("ls -l >> ./try_spawn.txt".into());
    task_builder
        .set_task_id(3)
        .set_frequency_repeated_by_cron_str("*/1 * * * * * *")
        .set_maximum_running_time(10)
        .set_maximum_parallel_runnable_num(1)
        .spawn(body)
```
when use schedule like  "*/3 * * * * * *",that run task every 3 second, I got a error
```rust
fn build_task_async_execute_process() -> Result<Task, TaskError> {
    let mut task_builder = TaskBuilder::default();

    let body = unblock_process_task_fn("ls -l >> ./try_spawn.txt".into());
    task_builder
        .set_task_id(3)
        .set_frequency_repeated_by_cron_str("*/3 * * * * * *")
        .set_maximum_running_time(10)
        .set_maximum_parallel_runnable_num(1)
        .spawn(body)
```
error like this:
```
create_async_fn_body!
Error: TaskInstance event get failed.

Caused by:
    receiving from an empty channel

```

**Desktop (please complete the following information):**
 - OS: linux

**other**
Can you help me get more ditails for error?

**Comment by BinChengZhao** [comment]
> ```rust
> .set_frequency_repeated_by_cron_str("*/3 * * * * * *")
> ```

Hi friend I am in.

The reason you're getting this error is probably because, when the program runs to

`.next()?
 .cancel_with_async_wait()`

no task instance has been created yet.

It is recommended that you do not use `.next()` here because it will get the task instance non-blocking and return an error if there is no instance.

It is recommended that you use `next_with_wait()` or `next_with_async_wait()` .

**Comment by elderbig** [comment]
It does work,thanks a lot!
