### ISSUE TITLE
无法编译通过

### ISSUE THREAD

**Issue by Ruilkyu** [BinChengZhao/delay-timer#3]
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/lr/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/delay_timer-0.2.1/src/lib.rs:205:1
    |
205 | #![feature(linked_list_cursors)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /Users/lr/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/delay_timer-0.2.1/src/lib.rs:206:1
    |
206 | #![feature(doc_cfg)]
    | ^^^^^^^^^^^^^^^^^^^^

error[E0658]: use of unstable library feature 'split_inclusive'
   --> /Users/lr/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/delay_timer-0.2.1/src/utils/parse.rs:149:52
    |
149 |         let mut sub_command_inner = command.trim().split_inclusive(angle_bracket).rev();
    |                                                    ^^^^^^^^^^^^^^^
    |
    = note: see issue #72360 <https://github.com/rust-lang/rust/issues/72360> for more information

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0554, E0658.
For more information about an error, try `rustc --explain E0554`.
error: could not compile `delay_timer`.

**Comment by BinChengZhao** [comment]
请使用最新的 nightly 工具链进行编译。

原因:
目前因为引入了std几个最新的feature  他们还没有稳定到std , 如 `linked_list_cursors` 与 `doc_cfg`  。

在下个版本中会彻底stable， 最低编译器版本应该 `1.51.*` 。

**Comment by BinChengZhao** [comment]
> error[E0554]: `#![feature]` may not be used on the stable release channel
> --> /Users/lr/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/delay_timer-0.2.1/src/lib.rs:205:1
> |
> 205 | #![feature(linked_list_cursors)]
> | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> error[E0554]: `#![feature]` may not be used on the stable release channel
> --> /Users/lr/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/delay_timer-0.2.1/src/lib.rs:206:1
> |
> 206 | #![feature(doc_cfg)]
> | ^^^^^^^^^^^^^^^^^^^^
> 
> error[E0658]: use of unstable library feature 'split_inclusive'
> --> /Users/lr/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/delay_timer-0.2.1/src/utils/parse.rs:149:52
> |
> 149 | let mut sub_command_inner = command.trim().split_inclusive(angle_bracket).rev();
> | ^^^^^^^^^^^^^^^
> |
> = note: see issue #72360 [rust-lang/rust#72360](https://github.com/rust-lang/rust/issues/72360) for more information
> 
> error: aborting due to 3 previous errors
> 
> Some errors have detailed explanations: E0554, E0658.
> For more information about an error, try `rustc --explain E0554`.
> error: could not compile `delay_timer`.

请使用最新的 nightly 工具链进行编译。

原因:
目前因为引入了std几个最新的feature 他们还没有稳定到std , 如 linked_list_cursors 与 doc_cfg 。

在下个版本中会彻底stable， 最低编译器版本应该 1.51.* 。

**Comment by Ruilkyu** [comment]
好的，感谢！
