### ISSUE TITLE
How to complete this demo with  delay-timer?

### ISSUE THREAD

**Issue by zwl1619** [BinChengZhao/delay-timer#31]
Code is as follow, questions are in the code.

Cargo.toml
```
[dependencies]
delay_timer = "0.10.1"
```

main.rs
```

use delay_timer::prelude::*;
use anyhow::Result;
use smol::Timer;
use std::time::Duration;



fn main() {
     //1、a timer start from 1 to 50000 millisecond.
            //let mut current_time= 1;

     //2、if the current_time equals some numbers, do somethings.
            if current_time =2000 {
                //do something 1
            } 
            if current_time =39999 {
                //do something 2
            } 
            //...
   
}
```

**Comment by elderbig** [comment]
example for `delay-timer/examples/demo.rs`, execute like

```
cargo run --package delay_timer --example demo --features=full
```
there is a annotation in the mod.

**Comment by BinChengZhao** [comment]
> Code is as follow, questions are in the code.
> 
> Cargo.toml
> 
> ```
> [dependencies]
> delay_timer = "0.10.1"
> ```
> 
> main.rs
> 
> ```
> 
> use delay_timer::prelude::*;
> use anyhow::Result;
> use smol::Timer;
> use std::time::Duration;
> 
> 
> 
> fn main() {
>      //1、a timer start from 1 to 50000 millisecond.
>             //let mut current_time= 1;
> 
>      //2、if the current_time equals some numbers, do somethings.
>             if current_time =2000 {
>                 //do something 1
>             } 
>             if current_time =39999 {
>                 //do something 2
>             } 
>             //...
>    
> }
> ```

In this case you use `tokio::time:sleep`, which would be better suited than `delay-timer`, `delay-timer` which manages periodic tasks and controls the number of concurrent tasks.

Your need is for random time intervals, suitable for different sleep schemes.
