### ISSUE TITLE
The TimerEvent::AppendTaskHandle event should always be sent before The TimerEvent::FinishTask event.

### ISSUE THREAD

**Issue by gamife** [BinChengZhao/delay-timer#45]
**Describe the bug**
When the task instance is running too fast, The TimerEvent::FinishTask event will be sent before The TimerEvent::AppendTaskHandle event. Subsequent task instances will not run again.

**To Reproduce**
1.  add `tokio::time::sleep(std::time::Duration::from_secs(2)).await` before
https://github.com/BinChengZhao/delay-timer/blob/1fd9d1751117ea628f44f7da4837b067005e02d7/src/timer/timer_core.rs#L343
2. run a repeat task with maxinum_parallel_runnable_num = 1;
3. If the task instance ends in less then 2 second, it will get `parallel_runnable_num>=maxinum_parallel_runnable_num doesn't run it`.

**Expected behavior**
Subsequent task instances can run again.

**Comment by BinChengZhao** [comment]
Thank you @gamife  very much for your support of the project. Due to work reasons, it is difficult for me to find time to do the open-source project now. Would like to invite you as the maintainer, I wonder if it is convenient for you

**Comment by BinChengZhao** [comment]
Thank you @gamife very much for your support of the project. Due to work reasons, it is difficult for me to find time to do the open-source project now. Would like to invite you as the maintainer, I wonder if it is convenient for you

**Comment by gamife** [comment]
> Thank you @gamife very much for your support of the project. Due to work reasons, it is difficult for me to find time to do the open-source project now. Would like to invite you as the maintainer, I wonder if it is convenient for you

Thank you very much for the invitation and for all the hard work you’ve put into this project. However, I don’t have enough experience and my abilities are limited to take on this responsibility. I suggest you find someone else who is capable of taking on this position.
