### ISSUE TITLE
feature requests: update deps

### ISSUE THREAD

**Issue by greenhat616** [BinChengZhao/delay-timer#49]
such as:
`event-listener` which has `^4` released
`lru` which has `^0.12.0` released - introduced BC, and need manually fix.
`dashmap` which has `^5` released

**Comment by BinChengZhao** [comment]
> such as: `event-listener` which has `^4` released `lru` which has `^0.12.0` released - introduced BC, and need manually fix. `dashmap` which has `^5` released

Your request will be completed in my spare time. Thank you for your support for the project!

**Comment by BinChengZhao** [comment]
@greenhat616  Hello my friend related dependencies have been updated to the latest :)
