### ISSUE TITLE
CandyCronStr怎么设置北京时间

### ISSUE THREAD

**Issue by Ruilkyu** [BinChengZhao/delay-timer#5]

**Comment by BinChengZhao** [comment]
> _No description provided._

@Ruilkyu 你的意思是cron-expression迭代采用自定义时区吧，目前统一用的是Utc时区，需要的话近期我再buider上开发一个api，支持默认采用（北京时间或格林尼治时间），到时候你就可以通过Local标志，使用北京时间了。


You mean the cron-expression iteration uses a custom time zone, right? The current unified time zone is Utc, if needed, I will develop an api on buider in the near future to support the default adoption (Beijing time or GMT), by then you can use Beijing time by Local flag.

**Comment by Ruilkyu** [comment]
感谢！需要，这样更方便。

**Comment by BinChengZhao** [comment]
> 感谢！需要，这样更方便。

现在默认就是机器的本地时区，还有以下特性请开始体验吧：
Now (v0.3.0) the default is the machine's local time zone, and the following features Please start experiencing them :

1.Compilable at stable by conditional compilation.

2.Balancing performance and user experience (ajust CandyCronStr inner-type and add free-api for TaskBuilder).

3.Support custom setting of time zone.

4.Fix the clock too fast issue.

5.Use `next_second_hand` to solve a schedule problem.

**Comment by Ruilkyu** [comment]
OK！





------------------ 原始邮件 ------------------
发件人: BinCheng <notifications@github.com&gt;
发送时间: 2021年2月5日 19:50
收件人: BinChengZhao/delay-timer <delay-timer@noreply.github.com&gt;
抄送: rui <luruilkyu@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[BinChengZhao/delay-timer] CandyCronStr怎么设置北京时间 (#5)





  
感谢！需要，这样更方便。
  
现在默认就是机器的本地时区，还有以下特性请开始体验吧：
 Now (v0.3.0) the default is the machine's local time zone, and the following features Please start experiencing them :
 
1.Compilable at stable by conditional compilation.
 
2.Balancing performance and user experience (ajust CandyCronStr inner-type and add free-api for TaskBuilder).
 
3.Support custom setting of time zone.
 
4.Fix the clock too fast issue.
 
5.Use next_second_hand to solve a schedule problem.
