### ISSUE TITLE
rust 1.75版本与delay-timer 0.11.4版本不兼容，1.74.1没有问题

### ISSUE THREAD

**Issue by apiclouds** [BinChengZhao/delay-timer#50]
error[E0277]: the trait bound `StrSearcher<'_, '_>: DoubleEndedSearcher<'_>` is not satisfied
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/delay_timer-0.11.4/src/utils/parse.rs:371:83
    |
371 |         let mut sub_command_inner = command.trim().split_inclusive(angle_bracket).rev();
    |                                                                                   ^^^ the trait `DoubleEndedSearcher<'_>` is not implemented for `StrSearcher<'_, '_>`
    |
    = help: the following other types implement trait `DoubleEndedSearcher<'a>`:
              CharSearcher<'a>
              CharArraySearcher<'a, N>
              CharArrayRefSearcher<'a, 'b, N>
              CharSliceSearcher<'a, 'b>
              CharPredicateSearcher<'a, F>
    = note: required for `std::str::SplitInclusive<'_, &str>` to implement `DoubleEndedIterator`
note: required by a bound in `rev`
   --> /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/traits/iterator.rs:3397:5

error[E0599]: the method `next` exists for struct `Rev<SplitInclusive<'_, &str>>`, but its trait bounds were not satisfied
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/delay_timer-0.11.4/src/utils/parse.rs:374:14
    |
373 | /         sub_command_inner
374 | |             .next()
    | |             -^^^^ method cannot be called on `Rev<SplitInclusive<'_, &str>>` due to unsatisfied trait bounds
    | |_____________|
    | 
   --> /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/str/iter.rs:1216:1
    |
    = note: doesn't satisfy `_: DoubleEndedIterator`
   --> /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/iter/adapters/rev.rs:15:1
    |
    = note: doesn't satisfy `Rev<std::str::SplitInclusive<'_, &str>>: Iterator`
    |
    = note: the following trait bounds were not satisfied:
            `std::str::SplitInclusive<'_, &str>: DoubleEndedIterator`
            which is required by `Rev<std::str::SplitInclusive<'_, &str>>: Iterator`

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `delay_timer` (lib) due to 2 previous errors

**Comment by iwansyahp** [comment]
error doesn't occur when using rust 1.74

**Comment by BinChengZhao** [comment]
Hi guys, the issue has been fixed in V0.11.5 @dyxushuai @apiclouds  @iwansyahp

**Comment by iwansyahp** [comment]
thank you, @BinChengZhao!
