### ISSUE TITLE
UTC时间似乎有几分钟左右的偏差

### ISSUE THREAD

**Issue by Ruilkyu** [BinChengZhao/delay-timer#6]

**Comment by Ruilkyu** [comment]
Define "Self::PerDayFiveAclock => CandyCronStr("01 42 8 * * * *")"
but start在Self::PerDayFiveAclock => CandyCronStr("01 40 8 * * * *")

**Comment by BinChengZhao** [comment]
> mac：
> Define "Self::PerDayFiveAclock => CandyCronStr("01 42 8 * * * *")"
> But Start at "Self::PerDayFiveAclock => CandyCronStr("01 40 8 * * * *")"
> 
> linux:
> Define "Self::PerDayFiveAclock => CandyCronStr("01 42 8 * * * *")"
> But Start at "Self::PerDayFiveAclock => CandyCronStr("01 37 8 * * * *")"

 谢谢你的反馈，我已经定位到了问题，等新版发布的时候我来通知你（就是最近这几天）。

Thank you for your feedback, I have located the problem, I'll let you know when the new version is released (which is the last few days).

**Comment by Ruilkyu** [comment]
I now add a calibrator, but looking forward to your new version!

**Comment by Ruilkyu** [comment]
I now add a calibrator, but looking forward to your new version!

**Comment by BinChengZhao** [comment]
> I now add a calibrator, but looking forward to your new version!

The problem has been fixed on v0.3.0!
