### ISSUE TITLE
are there plans to support distributed scheduling?

### ISSUE THREAD

**Issue by eliasyaoyc** [BinChengZhao/delay-timer#7]

**Comment by BinChengZhao** [comment]
> _No description provided._

Yes, while this lib is basically stable (probably v0.3.5), I will start developing a distributed scheduling system.

Containing a web admin panel, with multiple nodes distributed across the machines.

**Comment by eliasyaoyc** [comment]
sounds good, what can i do that help you  reach stablity quickly ?

**Comment by BinChengZhao** [comment]
> sounds good, what can i do that help you reach stablity quickly ?

#4 Thank you very much, I don't know how well you have mastered the asynchrony of rust, whether it is possible to encapsulate a state machine in order to make it easier for the user to dynamically cancel the running instances generated by the task through a handle, and expose the events that occur inside the specified task.

If you have some experience in this area, I can work with you to accomplish this. ：)

https://github.com/BinChengZhao/delay-timer/issues/4#issuecomment-767381469

**Comment by eliasyaoyc** [comment]
trytry

**Comment by BinChengZhao** [comment]
> trytry

    // Here is an expected implementation for DelayTimer::add_task , which is not yet determined.
    **Do you have a better opinion?**

    ///```
    // let delay_timer = DelayTimer::default();
    //
    // let join_handle = delay_timer.add_task(_).unwrap();
    //
    // let peek : Option<Peek<&Instance>> = join_handle.peek().await;
    // let peek : Result<Option<Peek<&Instance>>> join_handle.try_peek();
    //
    // let instance : Option<Intance> =  join_handle.next().await.unwrap();
    // let instance : Result<Option<Intance>> =  join_handle.try_next().unwrap();
    //
    // instance.cancel();
    //
    ///```

**Comment by eliasyaoyc** [comment]
i spent some time on the delay_timer these days，now i hava general idea of it.

**Comment by eliasyaoyc** [comment]
do you want use native async or build it yourself (e.g. executor、reactor etc.)

**Comment by eliasyaoyc** [comment]
haha，holidy is coming soon   do it

**Comment by BinChengZhao** [comment]
> i spent some time on the delay_timer these days，now i hava general idea of it.
> i think you gave me a good plan.

Thank you, we can work together in one piece, so the energy will be great.

**Comment by BinChengZhao** [comment]
[delicate](https://github.com/BinChengZhao/delicate)  Distributed scheduling platform, the first release has been stabilized, V1.1.0 will be released soon.    :)
